### ISSUE TITLE
Node that depends on embeded flow starts before all nodes in embedded flow complete

### ISSUE THREAD

**Issue by gchiappara** [azkaban/azkaban#1964]
I created this flow:
```
nodes:
  - name: jobB
    type: command
    config:
      command: echo -e "Hola"
    dependsOn:
      - jobA
  - name: jobA
    type: flow
    nodes:
      - name: jobA1
        type: command
        config:
          command: sleep 10
      - name: jobA2
        type: command
        config:
          command: sleep 600
```

I expect that jobB starts when bothn jobA1 **AND** jobA2 complete but this is not happening. What im doing wrong?

Thanks!
