### ISSUE TITLE
add properties file from azkaban-flow 2.0 

### ISSUE THREAD

**Issue by parkseulkee** [azkaban/azkaban#1998]
I want to use the same property in each .flow file.

* flow1.flow
```yaml
---
config:
    a: x
    b: y

nodes:
    - name: job1
       type: command
       config:
           command: echo ${a}, ${b}
```

* flow2.flow
```yaml
---
config:
    a: x
    b: y

nodes:
    - name: job2
       type: command
       config:
           command: echo ${b}, ${a}
```

Can I define the following variables as one file?

```
a: x
b: y
```
