### ISSUE TITLE
import subflows from seperate YAML file. Flow 2.0

### ISSUE THREAD

**Issue by ismailsimsek** [azkaban/azkaban#2056]
Hi 
Thank you for the great work with Flow 2.0 
is it possible to define a sub-flow in its own yaml file and import sub-flow into parent Flow. 

its also mentioned here #1525

```
config: 
  failure.emails: aaaaa@ppro.com
  success.emails: aaaaa@ppro.com
nodes: 
  !include FlowA.flow

  - name: jobC
    type: noop
    dependsOn:
      - FlowA
```
FlowA.flow
```
- name: DM_Flow
  type: flow

  nodes: 
  - name: jobXXXX
    type: noop
```
