### ISSUE TITLE
Trigger by file watching 

### ISSUE THREAD

**Issue by jlefebure** [azkaban/azkaban#2076]
Hi, 

We (will) use Azkaban in my company to handle exports file with Spark. As there is a trigger plugin to listen from a Kafka instance, what about to implement a new plugin to trigger a job when one or multiples files which follow a pattern are created ? 

Something like

```yaml
trigger: # As usual
  maxWaitMins: 2880
  schedule:
    type: cron
    value: 0 0/2 * * * ?

  triggerDependencies:
  - name: dep1 # an unique name to identify the dependency
    type: file-watching # New trigger dep type
    params:
      filePattern: /in/EXPORT_0B90*.csv # Define the file pattern to listen
      chunksNumber: 4 # Number of chunks before to trigger the job
```

I know it's already possible to do that with Hadoop, and from a Spark script, but implement that kind of feature in Azkaban seems to be cleaner for me. Also for users which are not using Azkaban with Hadoop. 

As I am new to Azkaban, may be it is already possible by another way. Any suggestions are welcomed.
