### ISSUE TITLE
Process job cannot partition command correctly when the command contains '\'.

### ISSUE THREAD

**Issue by lcaaaat** [azkaban/azkaban#2167]
For example, there is a node like this:
```yaml
nodes:
  - name: hello
    type: command
    config:
        command: echo "\"Hello, world!\""
```
Then upload it and execute, but I cannot find the quote in the output. The output is like this:
```
\Hello, world!\
```

The reason is **azkaban.jobExecutor.ProcessJob.partitionCommandLine** doesn't deal with the '\' in command. Even if the '"' behind the '\', it cannot be print.
