### ISSUE TITLE
failed to open "Java Job type-sample job" link in latest Azkaban doc

### ISSUE THREAD

**Issue by pennli** [azkaban/azkaban#2323]
I failed to open "Java Job type-sample job" link in latest Azkaban doc, it was unused recently.
could you please tell me how to config Java job type for Azkaban 3.76.0 in json format?
I have tried this way but it did not work at all:
```
nodes:
  - name: begin
    type: javaprocess
    config:
      java.class: azkabanTest.AzkbJavaPara
      main.args:  first,second
      classpath: /home/hadoop/Sqoop2Task/target/Sqoop2Task-0.0.1-SNAPSHOT.jar,/home/hadoop/Sqoop2Task/target/Sqoop2Task-0.0.1-SNAPSHOT-jar-with-dependencies.jar
```

looking forward your reply.
best regards.
