### ISSUE TITLE
all_done condition bug

### ISSUE THREAD

**Issue by sp-enric-fradera** [azkaban/azkaban#2484]
Hi,

I'm running the following test flow to illustrate the issue:

```
nodes:

    - name: job_a
      type: command
      config:
        command: asdf

    - name: job_b
      type: command
      dependsOn:
        - job_a
      config:
        command: ls

    - name: job_c
      type: command
      condition: all_done
      dependsOn:
        - job_b
      config:
        command: ls
```

What happens:
job_a -> FAILED
job_b -> CANCELLED
job_c -> CANCELLED

However, job_c has the condition "all_done" set and according to [the documentation](https://azkaban.readthedocs.io/en/latest/conditionalFlow.html#condition-on-job-status-macro) it should execute when it's dependencies are cancelled, which is the case.

Am I doing something wrong? This looks like a bug to me. Also, I'm running Azkaban 3.70.2 at the moment.

Thanks!
