### ISSUE TITLE
How to config 'retry' in flow 2.0 ?

### ISSUE THREAD

**Issue by partoneplay** [azkaban/azkaban#2503]

**Comment by ypadron-in** [comment]
It can be configured at flow level and job level. At flow level it will be applied to all jobs.

Flow level usage:
```
config:
  failure.emails: a@a.com
  retries: 2   # <-- here
nodes:
  - name: jobA
    type: command
    config:
      command: pwd
    dependsOn:
      - jobB
...
```

Job level usage:
```
config:
  failure.emails: a@a.com
nodes:
 - name: jobC
    type: command
    config:
      command: bash ./myScript
      retries: 2  # <-- here
...
```
