### ISSUE TITLE
[Feature Request] add "cleanup" or "finally" job to handle cleanup of flow in the event of failure

### ISSUE THREAD

**Issue by wacosta-harman** [azkaban/azkaban#44]
I would like to have a flag or some other indicator that would label a job as a "cleanup" job that would run whether or not the preceding jobs failed.  Kind of like a "finally" block in Java.  This would allow things like cleanup up an EMR cluster in the event of failed Hadoop job.

**Comment by Dima1224** [comment]
+1 for me as well. 

Has anybody found a good way of working around this? My use case is the same as @wacosta-harman.

**Comment by lynnfi** [comment]
+1 for my project.
Have you found a good way of working around this? @Dima1224

**Comment by Dima1224** [comment]
@lynnfi no, I haven't found a good workaround. We were forced to fork and implement the functionality ourselves.

**Comment by lynnfi** [comment]
@Dima1224 Thanks，I write a python_spider script to help me do this.And I have noticed many people recommend “airflow”,or you may try it~

**Comment by juhoautio** [comment]
@Dima1224 any chance to share your fork code? This feature is going to implementation on our side as well, already next week (we also use a private fork).

**Comment by Dima1224** [comment]
Hi @juhoautio, unfortunately I can't since this was done for a company I don't work for any longer. Are you planning on merging your implementation into Azkaban?

**Comment by juhoautio** [comment]
We have now implemented this feature on our private fork.

UI was also modified to highlight these jobs:

![nayttokuva 2018-5-4 kello 15 00 51](https://user-images.githubusercontent.com/4446608/39626754-f678b38e-4fab-11e8-87d9-0d2a3661d1f5.png)

For example here we have set:
- Something bad in `sub-flow-start.job` to make it fail
- `cleanup=true` in `parallel3.job` and `example-flow.job`

You can see how other jobs were cancelled after the flow failed, but the "cleanup" jobs were still run:

![nayttokuva 2018-5-4 kello 14 59 45](https://user-images.githubusercontent.com/4446608/39626782-0c9086e2-4fac-11e8-896d-3f4bbb6f4445.png)

**Comment by juhoautio** [comment]
Maybe we could prepare a pull request, if repo owners are interested in having this feature.

@ameyamk @HappyRay @chengren311 – what do you say?

**Comment by HappyRay** [comment]
@juhoautio 

Thanks.

This seems to be a useful feature. 

However, I just started resuming the work on DAG engine rewrite. #1486
I would prefer implementing additional features after we have a stronger foundation. 
In the meantime, I would be interested in your design and experience using it.

**Comment by reallocf** [comment]
This looks very cool - I like the caution symbol as a UI element (I'm not sure if caution correlates well to cleanup, but it certainly looks cool! 😄).

Another question on top of Ray's, how does this handle all the various states an Azkaban flow can be in? For example, if a kill is called on the flow, does it still execute the clean-up steps?

Also, if a flow fails before a subflow is started, do the clean-up steps in the subflow still get executed?

I'd also be interested in the design. Good work @juhoautio!

**Comment by juhoautio** [comment]
Thanks @reallocf.

Hehe, the ⚠️ symbol was put there mostly to warn users that that they probably don't want to disable the cleanup jobs when preparing an execution and manually disabling some jobs.

If the flow is killed, cleanup jobs are still run. We added a new "Force kill" button that can be used to stop even kill cleanup jobs if needed.

For sub-flows this is natural: if a sub-flow has _not_ started at all, cleanup jobs inside that sub-flow are not executed. If a (sub-)flow has started, then any cleanup jobs inside that flow are always run. Cleanup property can also be inherited from parent etc. As you can imagine this is quite powerful in possibilities that it offers.

> I'd also be interested in the design

I wonder what you mean by that?

**Comment by juhoautio** [comment]
@HappyRay:

> However, I just started resuming the work on DAG engine rewrite

That's great news!

Indeed our implementation of cleanup jobs touches the flow execution logic, which makes your concern valid. It will be much easier to reason about the changes required for the cleanup implementation after that.

**Comment by firemonk9** [comment]
Any update on when this issue will be merged into main branch ?

**Comment by juhoautio** [comment]
@djaiswal83 what do you think about this? Especially https://github.com/azkaban/azkaban/issues/44#issuecomment-386580880 & could you maybe comment on the DAG engine rewrite? Is it still planned, or has that idea item been dropped?

**Comment by djaiswal83** [comment]
We do not have anything in the pipeline to address this.

**Comment by juhoautio** [comment]
@djaiswal83 sure. We have this implemented. Would you like to have it?

**Comment by djaiswal83** [comment]
That would be awesome!

**Comment by MingJunDuan** [comment]
+1 for me, That's very nice.

**Comment by djaiswal83** [comment]
@juhoautio would you be willing to bring this feature?

**Comment by juhoautio** [comment]
@djaiswal83 yes, but I thought I’d wait for my open PRs to be completed first.

**Comment by juhoautio** [comment]
@djaiswal83 Actually, does the new [Conditional Workflow](https://azkaban.readthedocs.io/en/latest/conditionalFlow.html) feature allow doing this simply by using an `all_done` condition?

I haven't tried it myself yet.

**Comment by juhoautio** [comment]
I tested the conditional workflow. It doesn't allow a "finally" like behavior because the [job status macros](https://azkaban.readthedocs.io/en/latest/conditionalFlow.html#condition-on-job-status-macro) are only evaluated against the immediate parent jobs (_"i.e. the dependsOn section"_).

Here's a simple example first:

```yaml
---
nodes:
  - name: shell_echo
    type: command
    config:
      command: echo "This is an echoed text."
  - name: shell_pwd
    type: command
    config:
      command: pwd
  - name: shell_bash
    type: command
    config:
      command: bash ./sample_script.sh
  - name: shell_end
    type: noop
    dependsOn:
      - shell_pwd
      - shell_echo
      - shell_bash
    condition: all_done
```

<img width="596" alt="Näyttökuva 2020-6-26 kello 20 42 04" src="https://user-images.githubusercontent.com/4446608/85885752-87b2de00-b7ed-11ea-8598-acac6f10e2a1.png">

This matches the "cleanup" behavior! `shell_end` was executed even though `shell_bash` failed.

But then, another example where an additional job is added between failing job & conditional job:

```yaml
---
nodes:
  - name: shell_echo
    type: command
    config:
      command: echo "This is an echoed text."
  - name: shell_pwd
    type: command
    config:
      command: pwd
  - name: shell_bash
    type: command
    config:
      command: bash ./sample_script.sh
  - name: shell_end
    type: noop
    dependsOn:
      - shell_pwd
      - shell_echo
      - shell_bash
  - name: shell_end_real
    type: noop
    dependsOn:
      - shell_end
    condition: all_done
```

<img width="571" alt="Näyttökuva 2020-6-26 kello 20 42 11" src="https://user-images.githubusercontent.com/4446608/85886175-33f4c480-b7ee-11ea-8557-d46b8d6d98f0.png">

Now `shell_end_real` was not run, because `shell_end` didn't have special conditions and was cancelled.

I wonder if that's a bug actually? The documentation says this:

> all_done: FAILED, KILLED, SUCCEEDED, SKIPPED, FAILED_SUCCEEDED, CANCELLED

In this case the status of `shell_end` was indeed `CANCELLED` – shouldn't `shell_end_real` be run then?

The same thing seems to happen if `shell_end` is SKIPPED:

<img width="578" alt="Näyttökuva 2020-6-26 kello 20 49 49" src="https://user-images.githubusercontent.com/4446608/85886368-a06fc380-b7ee-11ea-900c-c0b66d2cff74.png">

----

In any case, **an important difference between conditional workflow and "cleanup" is kill handling**:
- conditional workflow: if a flow is killed, all jobs are cancelled regardless of possible conditions
- "cleanup" jobs (as proposed here): all "cleanup" jobs are completed before flow state is finalized from KILLING to KILLED.

Does it make sense to maintain "cleanup" feature and conditional workflow separately? Maybe the conditional workflow could be extended to support a new condition like `kill_ignored`, which would simply mean the same thing as the cleanup property that was proposed here?
